name: Custom XML Linter

on:
  push:
    paths:
      - 'XML/**/*.xml'
  pull_request:
    paths:
      - 'XML/**/*.xml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install lxml
    
    - name: Run custom linter
      run: python Scripts/custom_linter.py
