name: Output Category Stats

on:
  push:
    branches:
      - main

jobs:
  output-stats:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run stats script
      env:
        INPUT_DIR: './XML/beitraege' # Path to your XML files directory
        OUTPUT_FILE: './stats.txt'   # Output file for stats
      run: |
        python Scripts/stats.py
        cat ./stats.txt # Output stats to console

    - name: Upload stats artifact
      uses: actions/upload-artifact@v3
      with:
        name: category-stats
        path: ./stats.txt # Path to the stats file
